// export const EMAIL_ERROR = "EMAIL_ERROR";
// export const PASSWORD_ERROR = "PASSWORD_ERROR";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SET_LOGGEDIN_USER = "SET_LOGGEDIN_USER";
