// export const EMAIL_ERROR = "EMAIL_ERROR";
// export const PASSWORD_ERROR = "PASSWORD_ERROR";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SET_LOGGEDIN_USER = "SET_LOGGEDIN_USER";

// dental shop actions 
export const SHOPPING_ITEM_INCREASE = "INCREASE_SHOPPING_ITEM"
export const SHOPPING_ITEM_DECREASE = "DECREASE_SHOPPING_ITEM"
export const SHOPPING_ITEM_REMOVE = "REMOVE_SHOPPING_ITEM"